### PR TITLE
Add Swagger Socket Java JSR-356 Client

### PR DESCRIPTION
**Pull request by starlightknight**
@elakito - as discussed via email, this patch provides a Java JSR-356 based Swagger Socket Client.

This is an initial draft of a client that offers single / batch requests, with optional auto-deserialization with jackson. This has been tested with the Tomcat 8 Client/Server JSR-356 Library (tests provided against an embedded container).

### CODE REVIEW

**Comment by elakito** [comment]
@starlightknight  thanks!

**Comment by elakito** [comment]
@starlightknight this client needs to be aligned with the current asynchronous API.
we don't need a special handling for the server side if we let atmosphere pick jsr356.

**Comment by starlightknight** [comment]
@elakito I tried to go the async route originally. The reason I ended up coding it the way that it is now is that JSR-356 does not guarantee thread safety on the async methods. In particular, I encountered the following issue with Tomcat 8 when using async writes, even when I was syncing up the writes with a re-entrant lock: https://bz.apache.org/bugzilla/show_bug.cgi?id=56026

The current way was the only way I was able to get it reliably working under high load, but I am open to suggestion if you have ideas on how to work around this. When I would load test with a JMH benchmark, there were failures doing async w/ re-entrant lock, though it could have been a bug in my implementation; using the current route, I never had any failures.

**Comment by elakito** [comment]
@starlightknight isn't the issue mentioned for tomcat about using the client instance concurrently and not about a single thread successively sending messages over the client, no?

What I meant with my previous comment is why the user of the client instance needs to wait for responses and there is no API to get a future or pass a callback to receive responses later?

**Comment by starlightknight** [comment]
@elakito Oh i see! That's a good point, it should be easy to add. Internally its already using a Future with its count down latch, its just not exposed to the user. We could split out that class and add a method that returns the future instead of waiting. I will try to get to this soon.

**Comment by elakito** [comment]
@starlightknight thanks.

**Pull request merged**
